### ISSUE TITLE
[bj-share] Unable to perform manual search in Sonarr (no results)

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Indexers#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When performing a manual search in Sonarr, it will return no results from bj-share, even if a release for the episode/season exist in the tracker. Sonarr/Prowlar won't show any errors on the UI. The search link for the tracker in Prowlarr's history works if clicked. Manual search in Prowlarr UI also works.

### Expected Behavior

Return releases for a manual search in Sonnar if a release is available in bj-share

### Environment

```markdown
- OS: Ubuntu 20 arm7
- Prowlarr: 1.3.2.3006
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Brave
- Sonarr: 3.0.10.1567; mono 6.8.0.105
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace (1).txt](https://github.com/Prowlarr/Indexers/files/11338164/prowlarr.trace.1.txt)
[sonarr.trace.txt](https://github.com/Prowlarr/Indexers/files/11338205/sonarr.trace.txt)

[AB#4908](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4908)

**Comment by jaum20** [comment]
Aditional info:

![image](https://user-images.githubusercontent.com/36702273/234745118-fc770a66-424f-4521-af13-19294abf7c77.png)

**Comment by bakerboy448** [comment]
```
	Line  86: 2023-04-26 20:46:07.0|Info|ReleaseSearchService|Searching indexer(s): [Bj-Share] for Term: [Chosen 2017] for Season / Episode:[S03], Offset: 0, Limit: 100, Categories: [5000, 5050]
	Line  93: 2023-04-26 20:46:07.0|Info|Cardigann|Adding request: https://bj-share.info/torrents.php?filter_cat[2]=1&filter_cat[6]=1&filter_cat[8]=1&filter_cat[13]=1&filter_cat[14]=1&filter_cat[16]=1&filter_cat[17]=1&searchstr=Chosen+2017+&freetorrent=
	Line 277: 2023-04-26 20:46:18.1|Info|ReleaseSearchService|Searching indexer(s): [Bj-Share] for Term: [Chosen] for Season / Episode:[S03], Offset: 0, Limit: 100, Categories: [5000, 5050]
	Line 282: 2023-04-26 20:46:18.1|Info|Cardigann|Adding request: https://bj-share.info/torrents.php?filter_cat[2]=1&filter_cat[6]=1&filter_cat[8]=1&filter_cat[13]=1&filter_cat[14]=1&filter_cat[16]=1&filter_cat[17]=1&searchstr=Chosen+&freetorrent=
```

We intentionally remove the season parameters.  You'll need to discuss with the site why they return random / recently uploaded results if there are no results found; not a Prowlarr issue

@mynameisbogdan I don't see an issue here and bj-share simply returns random results - similar to eztv etc - if no results for the series exist. Feel free to re-open if you disagree

https://github.com/Prowlarr/Indexers/blob/01223ec2a85bf441f4fb7cc5de5f4c4910000b7e/definitions/v7/bjshare.yml#L73-L82
```yml
  keywordsfilters:
    - name: re_replace
      args: ["(S[0-9]+E[0-9]+|S[0-9]+)", ""] # remove SXXEXX or SXX from search

  rows:
    # If the category is a TV show/Anime, there's a necessity to filter the results by season/episode to not show all of them
    selector: "table.torrent_table > tbody > tr:not(tr.colhead).group,
              table.torrent_table tbody tr:not(tr.colhead):contains('{{ .Query.Episode }}')"
    filters:
      - name: andmatch
 ```
