### ISSUE TITLE
Hebits indexer remove imdbid from tv-search mode

### ISSUE THREAD

**Issue by BuSHari** [Prowlarr/Indexers#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When searching for epsidoes from sonarr i'll get all episodes of a show because it search bu imdbid, need to use with q

### Describe the solution you'd like

Please remove imdbid from tv-search mode, for example:
```yml
  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]
```

### Describe alternatives you've considered

No alternative, see also issue in Jackett:
https://github.com/Jackett/Jackett/issues/15224

### Anything else?

No
